#!/usr/bin/env bash
# this code help us to select some lines and and fizz and buzz to them
for i in {1..100}; do if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]; then echo FizzBuzz; elif [ $((i%3)) -eq 0 ]; then echo Fizz; elif [ $((i%5)) -eq 0 ]; then echo Buzz; else echo "$i"; fi; done

