#!/usr/bin/env bash
# this code help us to tell the story of passwd
while IFS=":" read -r user pass _ gid desc home shell; do echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $user's place is protected by the passcode $pass, more info about the user here: $desc"; done < /etc/passwd
