#!/usr/bin/env bash
# Dig the data: group by IP and HTTP status code

file="${1:-apache-access.log}"

awk '{count[$1" "$9]++}
     END {
         for (pair in count)
             printf "%8d %s\n", count[pair], pair
     }' "$file" | sort -nr
