#!/usr/bin/env bash
# this code help us print bad luck after 4rd line and print good luck after 8th line
i=1; while [ $i -le 10 ]; do  if [ $i -eq 4 ]; then echo "bad luck"; elif [ $i -eq 8 ]; then echo "good luck"; else echo "Best School"; fi; ((i++)); done
