#!/usr/bin/env bash
# this code doing everything
PIDFILE="/var/run/myscript.pid"; echo "$$" > "$PIDFILE"; cleanup(){ rm -f "$PIDFILE"; exit 0; }; trap 'echo "I hate the kill command"; cleanup' SIGTERM; trap 'echo "Y U no love me?!";' SIGINT; trap 'cleanup' SIGQUIT; while true; do echo "To infinity and beyond"; sleep 2; done
